scheduler:
  addr: 'localhost'
  port: '80'
type: 'zmap'
args:
  probe:
    - 'localhost:8888'
    - 'localhost:9999'
  prefix_len: 4
  ipv6: 'disable'
  port: 
    - 443
    - 80
  rand_seed: 45
  method: 'optimize'
  args:
    -f: '"saddr"'
    -B: '1M'

