scheduler:
  addr: 'localhost'
  port: '80'
type: 'zMnG'
args:
  probe:
    - 'localhost:8888'
  target: 'list.txt'
  zmap:
    args:
      -M: 'ipv6_tcp_synscan'
      -f: '"saddr"'
      -p: '443'
  zgrab:
    type: 'tls'
