scheduler:
  addr: 'localhost'
  port: '80'
type: 'zmap'
db:
  username: 'admin'
  password: '1qaz@WSX#EDC'
  addr: 'http://192.168.1.114:11000'
  public_key: 
  private_key: 
  success_only: false
args:
  probe:
    - 'localhost:8888'
  target: 'list_v4.txt'
  ipv6: 'disable'
  port: 
    - 443
    - 80
  rand_seed: 45
  method: 'optimize'
  args:
    -f: '"saddr"'
    -B: '1M'

