scheduler:
  addr: 'localhost'
  port: '80'
type: 'lzr'
args:
  refresh_netinfo: false
  probe:
    - 'localhost:8888'
  target: 'list.txt'
  port: 443
  zmap:
    args:
      -M: 'ipv6_tcp_synscan'
      -f: '"saddr"'
  lzr:
    --handshakes: 'http,wait,tls'
    -f: '/dev/null'
