scheduler:
  addr: 'localhost'
  port: '80'
type: 'zMnG'
args:
  ipv6: 'disable'
  refresh_netinfo: false
  probe:
    - '192.168.0.100:8888'
  target: 'list_v4.txt'
  port: 443
  zmap:
    args:
      -f: '"saddr"'
  zgrab:
    type: 'tls'
